version: "3.7"

services:
  filebeat:
    container_name: filebeat
    build: .
    depends_on:
      - logstash
    networks:
      - filebeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      - SERVICE_ENV="development"
      - LOGSTASH_HOST="logstash:5044"

  logstash:
    container_name: logstash
    build: test/logstash
    depends_on:
      - elasticsearch
    networks:
      - filebeat
    ports:
      - "5044:5044"

  kibana:
    container_name: kibana
    build: test/kibana
    depends_on:
      - elasticsearch
    networks:
      - filebeat
    ports:
      - "5601:5601"

  elasticsearch:
    container_name: elasticsearch
    build: test/elasticsearch
    networks:
      - filebeat

  generate-logs:
    build: test/generate-logs

networks:
  filebeat:
